// Generated by CoffeeScript 1.6.2
(function() {
  var definition, pegjs;

  pegjs = require('pegjs');

  definition = "query =\n  segment:segment toDate:field_selector field:field {\n    return {\n      toDate: field.toDate || toDate,\n      segment: segment,\n      field: field.field,\n      component: field.component\n    };\n  }\n\nfield =\n  field:ref toDate:component_selector component:ref {\n    return {\n      toDate: toDate,\n      field:field,\n      component: component\n    };\n  }\n  /\n  field:ref {\n    return {\n      field: field,\n      component: null\n    };\n  }\n\ncomponent_selector\n  =\n    '^' { return false; }\n    /\n    '@' { return true; }\n\nfield_selector\n  =\n    '|' { return false; }\n    /\n    '@' { return true; }\n\nsegment =\n  chars:[a-z0-9]i+ {\n    return chars.join('');\n  }\n\nref =\n  digits:[0-9]+ {\n    return Number(digits.join(''));\n  }";

  module.exports = pegjs.buildParser(definition);

}).call(this);
