// Generated by CoffeeScript 1.6.2
(function() {
  var Component, Composed, Subcomponent,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Composed = require('./Composed');

  Subcomponent = require('./Subcomponent');

  Component = (function(_super) {
    __extends(Component, _super);

    function Component(raw) {
      this.raw = raw;
      this.assign(Subcomponent);
      return;
    }

    Component.prototype.delimiter = '&';

    Component.prototype.getSubcomponent = function(index) {
      return this.getPart(index);
    };

    return Component;

  })(Composed);

  module.exports = Component;

}).call(this);
