// Generated by CoffeeScript 1.6.2
(function() {
  var Message, fs, messageparser, _;

  fs = require('fs');

  _ = require('underscore');

  Message = require('./Message');

  messageparser = require('../definitions/message');

  module.exports = {
    parse: function(s) {
      var column, control_characters, e, line, message, _ref;

      try {
        _ref = messageparser.parse(s), message = _ref.message, control_characters = _ref.control_characters;
        return new Message(message, control_characters);
      } catch (_error) {
        e = _error;
        column = e.column, line = e.line, message = e.message;
        return {
          column: column,
          error: message,
          line: line
        };
      }
    }
  };

}).call(this);
