// Generated by CoffeeScript 1.6.2
(function() {
  var Field, Segment, _;

  _ = require('underscore');

  Field = require('./Field');

  Segment = (function() {
    function Segment(fields, control) {
      this.control = control;
      this.name = _.first(_.flatten(fields));
      this.fields = _.reduce(fields, function(memo, field) {
        memo.push(new Field(field, this.control));
        return memo;
      }, [], this);
    }

    Segment.prototype.getValue = function(index) {
      var _ref;

      return ((_ref = this.fields[index]) != null ? _ref.val() : void 0) || '';
    };

    Segment.prototype.getPart = function(index) {
      return this.fields[index];
    };

    Segment.prototype.toString = function() {
      return _.map(this.fields, function(field) {
        return field.toString();
      }).join(this.control.fields);
    };

    return Segment;

  })();

  module.exports = Segment;

}).call(this);
